// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_pet_pal/test/unit_test/adoption_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_pet_pal/domain/adoption_applications/adoption_applications.dart'
    as _i6;
import 'package:flutter_pet_pal/domain/adoption_applications/adoption_applications_repository.dart'
    as _i3;
import 'package:flutter_pet_pal/domain/auth/auth_failure.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AdoptionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdoptionRepository extends _i1.Mock
    implements _i3.AdoptionRepository {
  MockAdoptionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, List<_i6.AdoptionApplication>>>
      fetchApplications() => (super.noSuchMethod(
            Invocation.method(
              #fetchApplications,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.AuthFailure,
                        List<_i6.AdoptionApplication>>>.value(
                _FakeEither_0<_i5.AuthFailure, List<_i6.AdoptionApplication>>(
              this,
              Invocation.method(
                #fetchApplications,
                [],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.AuthFailure, List<_i6.AdoptionApplication>>>);

  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, _i6.AdoptionApplication>>
      fetchApplicationById(String? id) => (super.noSuchMethod(
            Invocation.method(
              #fetchApplicationById,
              [id],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.AuthFailure, _i6.AdoptionApplication>>.value(
                _FakeEither_0<_i5.AuthFailure, _i6.AdoptionApplication>(
              this,
              Invocation.method(
                #fetchApplicationById,
                [id],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.AuthFailure, _i6.AdoptionApplication>>);

  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, List<_i6.AdoptionApplication>>>
      fetchUserApplications() => (super.noSuchMethod(
            Invocation.method(
              #fetchUserApplications,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.AuthFailure,
                        List<_i6.AdoptionApplication>>>.value(
                _FakeEither_0<_i5.AuthFailure, List<_i6.AdoptionApplication>>(
              this,
              Invocation.method(
                #fetchUserApplications,
                [],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.AuthFailure, List<_i6.AdoptionApplication>>>);

  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, _i2.Unit>> createApplication(
          Map<String, dynamic>? applicationJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #createApplication,
          [applicationJson],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.AuthFailure, _i2.Unit>>.value(
            _FakeEither_0<_i5.AuthFailure, _i2.Unit>(
          this,
          Invocation.method(
            #createApplication,
            [applicationJson],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AuthFailure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, _i2.Unit>> updateApplication(
    String? id,
    _i6.AdoptionApplication? application,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateApplication,
          [
            id,
            application,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.AuthFailure, _i2.Unit>>.value(
            _FakeEither_0<_i5.AuthFailure, _i2.Unit>(
          this,
          Invocation.method(
            #updateApplication,
            [
              id,
              application,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AuthFailure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, _i2.Unit>> deleteApplication(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteApplication,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.AuthFailure, _i2.Unit>>.value(
            _FakeEither_0<_i5.AuthFailure, _i2.Unit>(
          this,
          Invocation.method(
            #deleteApplication,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AuthFailure, _i2.Unit>>);
}
