// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_pet_pal/test/unit_test/pet_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i7;
import 'dart:typed_data' as _i8;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_pet_pal/domain/auth/auth_failure.dart' as _i5;
import 'package:flutter_pet_pal/domain/pets/pet.dart' as _i6;
import 'package:flutter_pet_pal/domain/pets/pet_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PetRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPetRepository extends _i1.Mock implements _i3.PetRepository {
  MockPetRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, List<_i6.Pet>>> fetchPets() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPets,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.AuthFailure, List<_i6.Pet>>>.value(
                _FakeEither_0<_i5.AuthFailure, List<_i6.Pet>>(
          this,
          Invocation.method(
            #fetchPets,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AuthFailure, List<_i6.Pet>>>);

  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, _i6.Pet>> fetchPetById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPetById,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.AuthFailure, _i6.Pet>>.value(
            _FakeEither_0<_i5.AuthFailure, _i6.Pet>(
          this,
          Invocation.method(
            #fetchPetById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AuthFailure, _i6.Pet>>);

  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, _i2.Unit>> addPet(
    _i6.Pet? pet, {
    _i7.File? imageFile,
    _i8.Uint8List? webImage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPet,
          [pet],
          {
            #imageFile: imageFile,
            #webImage: webImage,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.AuthFailure, _i2.Unit>>.value(
            _FakeEither_0<_i5.AuthFailure, _i2.Unit>(
          this,
          Invocation.method(
            #addPet,
            [pet],
            {
              #imageFile: imageFile,
              #webImage: webImage,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AuthFailure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, _i2.Unit>> updatePet(
    String? id,
    _i6.Pet? updatedPet,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePet,
          [
            id,
            updatedPet,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.AuthFailure, _i2.Unit>>.value(
            _FakeEither_0<_i5.AuthFailure, _i2.Unit>(
          this,
          Invocation.method(
            #updatePet,
            [
              id,
              updatedPet,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AuthFailure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, _i2.Unit>> deletePet(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePet,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.AuthFailure, _i2.Unit>>.value(
            _FakeEither_0<_i5.AuthFailure, _i2.Unit>(
          this,
          Invocation.method(
            #deletePet,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AuthFailure, _i2.Unit>>);
}
